---
- name: copy containerizer config
  copy:
     src: containerizers
     dest: /etc/mesos-slave/containerizers

- name: copy timeout config
  copy:
     src: executor_registration_timeout
     dest: /etc/mesos-slave/executor_registration_timeout

- name: Start mesos-slave service
  service:
     name: mesos-slave
     state: started
     enabled: yes
