---
- name: Set hostname value
  hostname:
     name: "{{ hostName }}"

- name: Copy hosts file
  copy:
     src: hosts
     dest: /etc/

- name: Set up public key
  template:
     src: id_rsa.pub.j2
     dest: /root/.ssh/id_rsa.pub

- name: Set up private key
  template:
     src: id_rsa.j2
     dest: /root/.ssh/id_rsa
     mode: 0600

- name: Set up authorized keys
  template:
     src: authorized_keys.j2
     dest: /root/.ssh/authorized_keys
     mode: 0600

- name: Copy proxy config
  copy:
     src: proxy.sh
     dest: /etc/profile.d/
  notify: "reload proxy.sh"

- name: Copy yum config
  copy:
     src: yum.conf
     dest: /etc/

- name: Copy libevent-devel RPM file to server
  copy:
     src: libevent-devel-2.0.21-4.el7.x86_64.rpm
     dest: /tmp/libevent-devel-2.0.21-4.el7.x86_64.rpm

- name: Install libevent-devel
  yum:
     name: /tmp/libevent-devel-2.0.21-4.el7.x86_64.rpm
     state: present

- name: Copy mesosphere repo RPM file to server
  copy:
     src: mesosphere-el-repo-7-1.noarch.rpm
     dest: /tmp/mesosphere-el-repo-7-1.noarch.rpm

- name: Install mesosphere repo
  yum:
     name: /tmp/mesosphere-el-repo-7-1.noarch.rpm
     state: present

- name: Install docker
  yum:
     name: docker
     state: installed

- name: Start docker service
  service:
     name: docker
     state: started
     enabled: yes

- name: Create docker config directory
  file:
     path: /etc/systemd/system/docker.service.d
     state: directory
     recurse: yes

- name: Update docker proxy config
  copy:
     src: http-proxy.conf
     dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  notify: "restart docker"

- name: Install git
  yum:
     name: git
     state: installed
